package carrentalsystem;
public class FineReceipt extends javax.swing.JFrame {
    public FineReceipt(String name,String carId,String brand,String car,String color,int fee,String rentDate,String returnDate,int delayedDays,int fine) {
        initComponents();
        Receipt.setEditable(false);
        Receipt.setText("\n                          Car Rental System                  \n");
        Receipt.setText(Receipt.getText()+"--------------------------------------------------------------\n");
        Receipt.setText(Receipt.getText()+"                     JALAN TEKNOLOGI 5         \n");
        Receipt.setText(Receipt.getText()+"             TAMAN TEKNOLOGI MALAYSIA        \n");
        Receipt.setText(Receipt.getText()+"                   57000 KUALA LUMPUR           \n");
        Receipt.setText(Receipt.getText()+"                         +60121234567                    \n");
        Receipt.setText(Receipt.getText()+"--------------------------------------------------------------\n");
        Receipt.setText(Receipt.getText()+" Name:                                           "+name+"\n");
        Receipt.setText(Receipt.getText()+" License Plate:                             "+carId+"\n");
        Receipt.setText(Receipt.getText()+" Brand:                                           "+brand+"\n");
        Receipt.setText(Receipt.getText()+" Car Name:                                   "+car+"\n");
        Receipt.setText(Receipt.getText()+" Color:                                            "+color+"\n");
        Receipt.setText(Receipt.getText()+" Rent Date:                                    "+rentDate+"\n");
        Receipt.setText(Receipt.getText()+" Return Date:                                "+returnDate+"\n");
        Receipt.setText(Receipt.getText()+" Price:                                             "+fee+"\n");
        Receipt.setText(Receipt.getText()+" Delayed Days:                             "+delayedDays+"\n");
        Receipt.setText(Receipt.getText()+" Fine:                                              "+fine+"\n");
        Receipt.setText(Receipt.getText()+"--------------------------------------------------------------\n");
        Receipt.setText(Receipt.getText()+" Total amount:                             RM "+(fee+fine)+"\n\n");
        Receipt.setText(Receipt.getText()+"**************************************************\n");
        Receipt.setText(Receipt.getText()+"                     Thank you come again                      \n");
        Receipt.setText(Receipt.getText()+"**************************************************\n");
        Receipt.setText(Receipt.getText()+"                 SOFTWARE BY:NETBEANS                 \n");
        Receipt.setText(Receipt.getText()+"          CONTACT: contact@netbeans.com    \n");
        Receipt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Receipt = new javax.swing.JTextArea();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Receipt.setColumns(20);
        Receipt.setRows(5);
        jScrollPane2.setViewportView(Receipt);

        Cancel.setText("Ok");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(Cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextArea Receipt;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
